---
aap_public_ip: "3.80.34.169"
controller_credential_types:
  - name: AWS credentioals
    description: Test AWS Credential
    state: present
    inputs:
      fields:
      - type: string
        id: accesskey
        label: access key
        secret: true
      - type: string
        id: secretkey
        label: secret key
        secret: true
      required:
      - accesskey
      - secretkey
    injectors: 
      extra_vars: 
        accesskey: !unsafe "{{ accesskey }}"
        secretkey: !unsafe "{{ secretkey }}"
controller_credentials:
  - name: Connecting to the server
    description: Credentials for GitLab
    organization: Default
    credential_type: Machine
    inputs:
      username: "{{ user_name }}"
      ssh_key_data: "{{ ssh_private_key | default(omit) }}"
      
    
