---
aap_public_ip: "54.80.215.47"
controller_credential_types:
  - name: AWS credentioals
    description: Test AWS Credential
    state: present
    inputs:
      fields:
      - type: string
        id: accesskey
        label: access key
        secret: true
      - type: string
        id: secretkey
        label: secret key
        secret: true
      required:
      - accesskey
      - secretkey
    injectors: 
      extra_vars: 
        accesskey: !unsafe "{{ accesskey }}"
        secretkey: !unsafe "{{ secretkey }}"
    
