---
aap_public_ip: "54.80.215.47"
controller_credential_types:
  - name: AWS credentioals
    description: Test AWS Credential
    state: present
    inputs:
      fields:
      - type: string
        id: accesskey
        label: access key
        secret: true
      - type: string
        id: secretkey
        label: secret key
        secret: true
      required:
      - accesskey
      - secretkey
    injectors: 
      extra_vars: 
        accesskey: !unsafe "{{ accesskey }}"
        secretkey: !unsafe "{{ secretkey }}"
controller_credentials:
  - name: Connecting to the server
    description: Credentials for GitLab
    organization: Default
    credential_type: Machine
    inputs:
      username: ec2-user
      ssh_key_data: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAvD4e0e+dhMG1g2QOqQbPhwyq0jnR1A3spxwDQpW6AdhvZJfh
        ll64ikTDm2sHGYjyYm82Sco1Ep5cE6uYio9Idfv7c5rcPY6kxU5GMCBpk5h/IE7y
        InV0ktk4eO39TjhRCRe0J48Vzmdc5XtUMRlW0vaVqS10llVaOGtsyNqaOTx9xHft
        72aTefjDmHq4pt38kRXQnEtpn2LK8vLWuCfdZnrFkqtB7xRARL8pIG63HuOnYy81
        IKrJj0OkLwALQ1ZdVjQtn/cCAskeI2DavkJecf1SkjkvXQmxr8KUvtngBqVhARPg
        CWjOju8JEICI7+4wX/SSRRoWmjzBS/9neOiFAwIDAQABAoIBAETKttylonz3hWvk
        zu66THDgEjUNaD8Eb62KMS7OJNGz1NGAJ7KaHvp4srtDW67bOyj5128T9F0/fgq6
        NN6+Cg8D7RqMR1w/mrt4JXJFBhAoNJ0L/LTXE6jutRKMdnt1XTfjb7TdN2zcnThH
        37apue8SqhLPR8IAox3nNDQany226fRIC+T1Zo1SLQ6nx8uliQ7F+QfZKm0sF1qQ
        2PDP8Qnm0DRQNNFbDUPQ6RD/bEZgy3NqEooFZEyXyrcd8hfNWDU01AMPp+97KI8z
        ha+dD63RRx7kI9Ug7FMCoXNftFiIts5v4DP3ZJJqPbyfkPa4qbVgV6JqziShhzZc
        oIV+bBECgYEA9x1KhfaFn1SM4r9o/aQeWHXRdhuuPoLwX6CX/o+shW78l96QXfLO
        8wE6d8wp/oGoZly0m8YaDB5POoFeZnZBIegDJmV3D/eZpr5oONnonVCE/VfP1/1/
        YI6X+S/iEhUT2V7lmBNt9XDVw1K6l/yRmtXIcS2mO1vQPTIlmQIbnncCgYEAwwLo
        6Nk/PD77RusabS4WtKDYp2aH5PzzqgmPobDic1/31r9o1/RRzR2SG8q9R1s5/poe
        nE2MCJAv1E0lYfSH95I5OWzIufqQKHamXGFhvGWXUiBnC89sixtn1DWz+bkTqfm3
        Q36cM9jpRwk+mjI3cjkbYSyiIi6AOmQpeO4OtNUCgYEAvSM1M/2w3neHcdHRWTlx
        ZIGg9YZQQlZUBs1TKKrtACAnw1G9K7s5fLM2/hRNHBg/PUG9lvD0ZMwaFgyIpWHj
        jkEXkB7fF2CKwR5BhSn8KdRERegdFBNZmBzr4vUsUmzBiYFht5k/czmO03YRjVzq
        URlJ1p56+jnW08/7CPadDxcCgYBB+xQO5KJuoeinABj64+MuzlU/noNQSP2whHei
        f5S+8LOMZ0rz9mhO/DhZSulr4UPoDwFYZSyCITbtoASL9g6jB0hxU4s+0bZA2pRD
        IXfOJJlkYi47Yr0Y+/bPaDQyxBoRIrqNDaOQL04OiOQzi9YSwZuv70gURKOCHi2i
        CvnS2QKBgAMBeNUScfsM3HP0o7IMgT78JYgbP//TRaBcGfjHWndkRDYDJY886+kj
        fCoGuAIdE6gvbvRYCGJcmZ5SADe7/rksqVG6cDGEUPX7CXNKxGZzN0f/ch75dFCl
        fFLhY6dHpKSATuazXrkPv8lW0rtMwqSibwlt0TLnLjpC/Z1Eg+nh
        -----END RSA PRIVATE KEY-----
    
