- name: connect to ansible controlle
  hosts: localhost
  roles:
    - {role: infra.controller_configuration.credential_types, when: controller_credential_types is defined}
  vars:
    controller_hostname: "https://44.204.81.48"
    controller_username: "admin"
    controller_oauthtoken: "gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
   
  tasks:
    - name: connect to ansible controller
      ansible.builtin.uri: 
        url: https://44.204.81.48/api/v2/
        headers: 
          Content-Type: application/json
          Authorization: "Bearer gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
        validate_certs: false
    
