- name: connect to ansible controlle
  hosts: localhost
  tasks:
    - name: connect to ansible controller
      ansible.builtin.uri: 
        url: https://44.204.81.48/api/v2/
        headers: 
          Content-Type: application/json
          Authorization: "Bearer gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
        validate_certs: false
