- name: connect to ansible controlle
  hosts: localhost
  #roles:
   # - {role: infra.controller_configuration.credential_types, when: controller_credential_types is defined}
  vars:
    controller_hostname: "https://44.204.81.48"
    controller_username: "admin"
    controller_oauthtoken: "gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
    credential_type_payload:
      name: "AWS access key"
      description: "A credential type for AWS Access Key authentication"
      kind: "cloud"
      inputs:
        fields:
          - id: "access_key"
            label: "AWS Access Key"
            type: "string"
            secret: true
          - id: "secret_key"
            label: "AWS Secret Key"
            type: "string"
            secret: true
          - id: "region"
            label: "AWS Default Region"
            type: "string"
            secret: false
        required: ["access_key", "secret_key", "region"]
      injectors:
        extra_vars:
          accesskey: "AKIARZ5BND67P5653QOO"
          secretkey: "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"
          region: "us-east-1"
           
        
   
  tasks:
    - name: connect to ansible controller
      ansible.builtin.uri: 
        url: https://44.204.81.48/api/v2/
        headers: 
          Content-Type: application/json
          Authorization: "Bearer gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
        validate_certs: false

    - name: get the credentials types
      ansible.builtin.uri:
        url: "{{ controller_hostname }}/api/v2/credential_types/"
        method: post
        headers:
          Authorization: "Bearer gjyJzB5ekmrqLM3UfhVYerbMF0PXUl"
          Content-Type: "application/json"
          body: "{{ credential_type_payload }}"
          validate_certs: no
      register: result

    - debug: var=result
    
