- name: connect to ansible controlle
  hosts: localhost
  roles:
    - {role: infra.controller_configuration.credentials, when: controller_credentials is defined}
  vars:
    controller_hostname: "https://{{ aap_public_ip }}"
    controller_username: "admin"
    controller_oauthtoken: "Fooym5yPjS8tKQULR61PCK9abNLtGk"
    controller_validate_certs: false           
  tasks:

    #- debug: var=controller_credential_types
    #- name: connect to ansible controller
     # ansible.builtin.uri: 
      #  url: https://54.173.4.1/api/v2/
       # headers: 
        #  Content-Type: application/json
         # Authorization: "Bearer Fooym5yPjS8tKQULR61PCK9abNLtGk"
        #validate_certs: false
        

    
