- name: connect to ansible controlle
  hosts: localhost
  roles:
    - {role: infra.controller_configuration.credential_types, when: controller_credential_types is defined}
  vars:
    controller_hostname: "https://52.73.124.144"
    controller_username: "admin"
    controller_oauthtoken: "Fooym5yPjS8tKQULR61PCK9abNLtGk"
    controller_validate_certs: false           
  tasks:

    - debug: var=controller_credential_types
    - name: connect to ansible controller
      ansible.builtin.uri: 
        url: https://52.73.124.144/api/v2/
        headers: 
          Content-Type: application/json
          Authorization: "Bearer Fooym5yPjS8tKQULR61PCK9abNLtGk"
        validate_certs: false

    
