---
- hosts: localhost
  vars:
    package_install:
      - httpd
  tasks:
    - name: Install httpd
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_install }}"  
      register: install_status

    - name: Dsiplay the install stataus
      debug: var=install_status
